name: practice_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  calendar_date_picker2: ^1.0.2
  card_banner: ^0.0.1+2
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  cupertino_onboarding: ^1.2.0
  date_picker_plus: ^4.0.0
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  excel: ^4.0.2
  file_downloader_flutter: ^0.0.5
  fl_chart: ^0.68.0
  flame: ^1.17.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.2.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_local_notifications: ^17.1.2
  flutter_onboarding_slider: ^1.0.11
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  flutter_windowmanager: ^0.2.0
  game: ^0.0.5
  go_router: ^14.1.4
  google_maps_flutter: ^2.5.3
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  internet_connection_checker_plus: ^2.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loading_progress: ^1.0.2
  marquee: ^2.2.3
  open_filex: ^4.4.0
  path_provider: ^2.1.3
  pdf: ^3.10.8
  permission_handler: ^11.3.1
  progress_loading_button: ^2.0.2
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  reactive_date_range_picker: ^2.1.0
  retrofit: ^4.1.0
  rounded_loading_button_plus: ^3.0.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  skeletonizer: ^1.1.2+1
  syncfusion_flutter_datepicker: ^25.2.4
  timezone: ^0.9.3
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter_gen:
  output: lib/gen/
  line_length: 80
  package_parameter_enabled: true
  directory_path_enabled: true

  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/dragon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
