name: practice_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  add_to_cart_button: ^0.0.6
  animate_do: ^3.3.4
  animate_text: ^1.0.0
  animated_hint_textfield: ^1.0.3
  animated_read_more_text: ^0.0.6
  animated_text_kit: ^4.2.2
  audioplayers: ^6.0.0
  auto_animated: ^3.2.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  calendar_date_picker2: ^1.0.2
  card_banner: ^0.0.1+2
  clipboard: ^0.1.3
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  cupertino_onboarding: ^1.2.0
  date_picker_plus: ^4.0.0
  device_preview: ^1.2.0
  digital_signature_flutter: 0.0.3
  dio: ^5.4.3+1
  dot_navigation_bar: ^1.0.2
  dotted_border: ^2.1.0
  easy_localization: ^3.0.7
  easy_url_launcher: ^0.0.7
  excel: ^4.0.2
  file_downloader_flutter: ^0.0.5
  fl_chart: ^0.68.0
  flame: ^1.17.0
  flip_card: ^0.7.0
  floating_frosted_bottom_bar: ^0.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_carousel_widget: ^2.2.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_floating_bottom_bar: ^1.2.0
  flutter_infinite_marquee: ^1.0.0
  flutter_local_notifications: ^17.2.3
  flutter_native_splash: ^2.4.1
  flutter_onboarding_slider: ^1.0.11
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_seekbar: ^1.0.1
  flutter_svg: ^2.0.10+1
  flutter_windowmanager: ^0.2.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  internet_connection_checker_plus: ^2.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.39
  like_button: ^2.0.5
  loading_progress: ^1.0.2
  marquee: ^2.2.3
  month_year_picker: ^0.4.0+1
  open_filex: ^4.4.0
  path_provider: ^2.1.3
  pdf: ^3.10.8
  permission_handler: ^11.3.1
  progress_loading_button: ^2.0.2
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  reactive_date_range_picker: ^2.1.0
  record: ^5.1.2
  retrofit: ^4.1.0
  rounded_loading_button_plus: ^3.0.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  skeletonizer: ^1.1.2+1
  staggered_grid_view_flutter: ^0.0.4
  story: ^1.1.0
  syncfusion_flutter_charts: ^25.2.7
  syncfusion_flutter_datepicker: ^25.2.4
  timezone: ^0.9.3
  typewritertext: ^3.0.6
  typing_text: ^1.0.4
  upi_payment_qrcode_generator: ^1.4.0
  url_launcher: ^6.3.0
  vector_graphics: any
  wave: ^0.2.2
  widget_marquee: ^0.0.8

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

dependency_overrides:
  fading_edge_scrollview: ^4.1.1

flutter_native_splash:
  color: "#011307"
  branding: assets/images/g1.png
  image: assets/images/facebook_logo.png
  color_dark: "#563224"
  branding_bottom_padding_android: 50

flutter_gen:
  output: lib/gen/
  line_length: 80
  package_parameter_enabled: true
  directory_path_enabled: true

  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/dragon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: PlayWrite
      fonts:
        - asset: assets/fonts/PlaywriteMX-Regular.ttf
        - asset: assets/fonts/PlaywriteMX-ExtraLight.ttf
          weight: 400
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
